services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - mysql 
    volumes:
      - .:/usr/app 
      - node_modules:/usr/app/node_modules
    environment:
      NODE_ENV: development
    networks:
      - app-network

  mysql:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: password
    ports:
      - '3306:3306'

networks:
  app-network:
    driver: bridge

volumes:
  node_modules: